column_names_replacement_map = {'_t-': '_tm', '_t+': '_tp'}
ENDPOINT_URL = 'http://vast1.me-corp.lan'

IMG_COLS = [
            'main_features',
            'frontcornerleft_features',
            'frontcornerright_features',
            'rearcornerleft_features',
            'rearcornerright_features',
            'rear_features',
        ]
        
NPZ_COLS = [
    'boxes',
    'rearcornerright_semantic_t_2',
    'main_semantic',
    'main_semantic_t_2',
    'frontcornerleft_semantic',
    'frontcornerleft_semantic_t_2',
    'frontcornerright_semantic',
    'frontcornerright_semantic_t_2',
    'rear_semantic',
    'rear_semantic_t_2',
    'rearcornerleft_semantic',
    'rearcornerleft_semantic_t_2',
    'rearcornerright_semantic',
    'main_z',
    'main_z_t_2',
    'frontcornerleft_z',
    'frontcornerleft_z_t_2',
    'frontcornerright_z',
    'frontcornerright_z_t_2',
    'rear_z',
    'rear_z_t_2',
    'rearcornerleft_z',
    'rearcornerleft_z_t_2',
    'rearcornerright_z',
    'rearcornerright_z_t_2',
    'main_x',
    'main_x_t_2',
    'frontcornerleft_x',
    'frontcornerleft_x_t_2',
    'frontcornerright_x',
    'frontcornerright_x_t_2',
    'rear_x',
    'rear_x_t_2',
    'rearcornerleft_x',
    'rearcornerleft_x_t_2',
    'rearcornerright_x',
    'rearcornerright_x_t_2',
    'main_m_projection',
    'main_m_projection_t_2',
    'frontcornerleft_m_projection',
    'frontcornerleft_m_projection_t_2',
    'frontcornerright_m_projection',
    'frontcornerright_m_projection_t_2',
    'rear_m_projection',
    'rear_m_projection_t_2',
    'rearcornerleft_m_projection',
    'rearcornerleft_m_projection_t_2',
    'rearcornerright_m_projection',
    'rearcornerright_m_projection_t_2'
]
