# This workflow demonstrates the use of a generator step which produces a list of items as a result.
# This list is subsequently used for expanding the next step into multiple parallel steps.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: etay-bert-
  labels:
    extendedRun: "true"
spec:
  arguments:
    parameters:
    - name: projectname
      value: gal-in
    - name: hyperparams
      value: 'model.batch_size=512 model.learning_rate=0.001'
    - name: codepath
      value: /opt/ml/data/temp_code_files/{{workflow.parameters.projectname}}/code_archive.tar.gz
  volumes:
  - name: argo-aws-cred
    configMap:
      name: argo-aws-cred
  - name: argo-aws-config
    configMap:
      name: argo-aws-config
  - name: vast-data
    hostPath:
      path: /mobileye/ALGO_VAST/mobileye-team-angie/users/etay/huggingface/c4/en-raw/
      type: Directory
  - name: dshm
    emptyDir:
      medium: Memory
  entrypoint: s3-2-op
  templates:
  - name: s3-2-op
    steps:
    - - name: angie-exec
        template: angie-exec
  - name: angie-exec
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      gpu: nvidia-a100
    container:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: op-s3-storage
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: op-s3-storage
              key: secretKey
        - name: OP_S3_STORAGE
          valueFrom:
            secretKeyRef:
              name: op-s3-storage
              key: endpointurl
      imagePullPolicy: Always
      image: artifactory.sddc.mobileye.com/dl-algo-docker-release/pqdsbm:bert
      resources:
        requests:
          memory: 64Gi
          cpu: '16'
        limits:
          memory: 64Gi
          cpu: '16'
      command: [bash, -c]
      args:
        - >-
          sleep 9999999
      volumeMounts:
      - name: argo-aws-cred
        mountPath: /home/me.docker/.aws/credentials
        subPath: credentials
      - name: argo-aws-config
        mountPath: /home/me.docker/.aws/config
        subPath: config
      - name: dshm
        mountPath: /dev/shm
      - name: vast-data
        mountPath: /opt/ml/data/

